Repository wanderer179/Hacktober2021-files, pull requests merged in 2021-10, with the labels that each got.

#10 starsiamdsp9.cpp
  starsiamdsp9.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, c++

#17 Create starsnowden.cpp
  starsnowden.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#19 snowden_hack
  compoud _interest.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#27 Starwanderer.cpp
  Starwanderer.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#23 Create hcf.cpp
  hcf.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#26 Create fibonacci.cpp
  fibonacci.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#24 Create starshape.cpp
  starshape
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#25 Create compound interest.cpp
  compound interest.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#28 fibonacciwanderer.cpp
  fibonacciwanderer.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#29 compoundint.cpp
  compoundint.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#30 Create fibonaccidsp.cpp
  fibonaccidsp.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#31 Create hcfdsp.cpp
  hcfdsp.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#32 Create hcfsnow.cpp
  hcfsnow.cpp
Labels: hacktoberfest-accepted

#33 Create iAmHappy.cpp
  iAmHappy.cpp
Labels: hacktoberfest-accepted

#34 Create hcfwanderer.cpp
  hcfwanderer.cpp
Labels: hacktoberfest-accepted

#35 Create CIwanderer.cpp
  CIwanderer.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#38 Create soubhagyaCI.cpp
  soubhagyaCI.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#48 Create aryasd.py
  aryasd.py
Labels: hacktoberfest-accepted

#47 Create aryafg.py
  aryafg.py
Labels: hacktoberfest-accepted

#46 Create aryajk.py
  aryajk.py
Labels: hacktoberfest-accepted

#45 Create aryahc.py
  aryahc.py
Labels: hacktoberfest-accepted
